# Generated by Django 5.1.2 on 2024-10-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_categorias_descricao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receitas",
            name="ingredientes",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="favoritas",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="receitas",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="seguidos",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="Ingredientes",
        ),
        migrations.AddField(
            model_name="receitas",
            name="ingredientes",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="Usuarios",
        ),
    ]
