# Generated by Django 5.1.2 on 2024-11-04 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_receitas_ingredientes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.CharField(max_length=100)),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="receitas",
            name="imagem",
            field=models.ImageField(null=True, upload_to="img/"),
        ),
        migrations.AlterField(
            model_name="receitas",
            name="ingredientes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.ingredientes"
            ),
        ),
    ]
