# Generated by Django 5.1.2 on 2024-11-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_ingredientes_alter_receitas_imagem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredientes",
            name="quantidade",
        ),
        migrations.AddField(
            model_name="receitas",
            name="quantidade",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
