# Generated by Django 5.1.2 on 2024-11-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_quantidade_remove_receitas_ingredientes_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="quantidade",
        ),
        migrations.AddField(
            model_name="receitas",
            name="ingredientes",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
