# Generated by Django 5.1.2 on 2024-11-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_delete_quantidade_receitas_ingredientes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receitas",
            name="criador",
        ),
    ]
